### ISSUE TITLE
Refresh on ManageVault and Swap pages results in 404 Error

### ISSUE THREAD

**Issue by rowgraus** [Agoric/dapp-treasury#10]
Hitting 'refresh' on the manageVault page results in 404.  You can navigate back through Treasury.

**Comment by rowgraus** [comment]
https://images.zenhubusercontent.com/355354197/038cabf3-b7fa-4655-94cc-b6bb1da3f2e8/managevault404.mov

**Comment by katelynsills** [comment]
This is expected given that there is no actual page there (React is generating it), and we have no backend server. See https://stackoverflow.com/questions/27928372/react-router-urls-dont-work-when-refreshing-or-writing-manually

I think we need to either change our webpack or netify settings to send /* to index.html. I'll investigate further
