### ISSUE TITLE
In Chrome, Treasury application does not seem to connect to the wallet

### ISSUE THREAD

**Issue by rowgraus** [Agoric/dapp-treasury#19]
Connection works in Brave, but I have yet to see the Treasury connect to the wallet properly in Chrome.

Behavior:
Sits on this page:
![image.png](https://images.zenhubusercontent.com/5fd77cb9688d8a64c14e7e66/f70bf3f0-9f56-4356-858c-9ac06b13af4d)

Shows no errors in Console:
![image.png](https://images.zenhubusercontent.com/5fd77cb9688d8a64c14e7e66/8b14c045-5483-4ac2-9ed5-1e8207808b1f)

Have attempted hard refreshes and starting/stopping Ag solo

**Comment by rowgraus** [comment]
Started from fresh docker.  The Treasury dapp never asks to connect to the wallet.  If it's already connected, as in above post, it doesn't seem to pull information regardless.

![Chrome Treasury.gif](https://images.zenhubusercontent.com/5fd77cb9688d8a64c14e7e66/b1794ff1-84f7-45c5-ab40-4340b958d32a)

The gif stops at 60 seconds.  I let it hang for another 10 minutes with no change

**Comment by rowgraus** [comment]
Summarized attempt at isolation:

1) Brought down previous wallet docker-compose down -v
2) Started wallet set up from scratch with new faucet request /etc
3) Navigated to Treasury/wallet in Chrome normal window with adblock turned off for the treasury app - saw behavior above
4) Navigated to Treasury/wallet in Chrome incognito - saw behavior above
5) Navigated to Treasury/wallet in Brave, request was sent immediately to my wallet (shown in both Chrome instances as well)
6) Accepted connection in Brave-loaded wallet (reflected in Chrome instances as well)
7) In Brave Treasury window, collateral loaded successfully.  Neither of the Chrome Treasuries loaded

**Comment by michaelfig** [comment]
Here is a known good reload under Chrome, with some additional instrumentation.

![Screen Shot 2021-04-07 at 1.42.28 PM.png](https://images.zenhubusercontent.com/601d7c046a13c62380d6b088/4c64c12e-6e37-49de-9a5f-eae11c6238fc)
