### ISSUE TITLE
path issue when running agoric deploy exampleDeployScripts/api.js

### ISSUE THREAD

**Issue by tgrecojs** [Agoric/dapp-treasury#22]
### Problem
Seem to been running into an error when executing the following deploy script `agoric deploy exampleDeployScripts/api.js`. Once the deploy command fails, my shell shows the error message `Cannot find module '../ui/src/generated/installationConstants`, however, I can confirm that this folder/file is in fact present at this path.

### Solution
By prepending `./` to the path string, I was able to quickly deploy the api.js file without any issues. I'm not sure if this is something specific to me, or if this is an issue that others will also run into, so I thought it was worth mentioning. 

Below is the LOC I'm referring to:

https://github.com/Agoric/dapp-treasury/blob/dea0c80299c6f2c9c02b39354d2c981e938d41e3/exampleDeployScripts/api.js#L340

And here is the fix from within my fork of the code (doesn't want to embed for some reason 🤔) :

https://github.com/tgrecojs/dapp-treasury/blob/4d62cf6a8582f21853145ad5ab0e178c31ed7c3a/exampleDeployScripts/api.js#L340

**Comment by katelynsills** [comment]
Hi @tgrecojs, thanks for making the issue! Can you explain a little more about what you are trying to do? Are you deploying your own version of the treasury locally? Or deploying your own version to the devnet? Or just using the treasury?

Currently, the `exampleDeployScripts` aren't intended to be executed. The on-chain treasury is deployed via different functionality in agoric-sdk. But, we left them there as a starting point in case a user might want to play with the treasury locally, in which case they would need to modify them to fit their specific requirements. If you let me know what you intend, we can help you modify them. Thanks!

**Comment by tgrecojs** [comment]
hey @katelynsills! no problem at all.

At the moment I'm just exploring the treasury to strengthen my understanding of dapp development on top of agoric's platform. I was aware that files inside exampleDeployScripts were provided for developers to reference and build upon, but for some reason, I was under the impression that I still needed to deploy code to my local agoric blockchain for the UI to work properly, which I now know is not the case thanks to u clarifying the agoric-SDK's role in this.

I'll definitely reach out in the future if / when I have any specific questions but I think I'm all set for right now. 

Thanks again for the helpful insight!

**Comment by samsiegart** [comment]
Just updated the README to make the purpose of `exampleDeployScripts` more clear
