### ISSUE TITLE
Difficulty getting Treasury collateral page to load

### ISSUE THREAD

**Issue by rowgraus** [Agoric/dapp-treasury#24]
Working in Brave.  Treasury is connected and page hangs while attempting to load collateral types.  Stuck here:

![image.png](https://images.zenhubusercontent.com/5fd77cb9688d8a64c14e7e66/e0fbbe2c-c083-41d0-b3c7-511d8d99727a)

This was working an hour ago.

Here is the console:
![image.png](https://images.zenhubusercontent.com/5fd77cb9688d8a64c14e7e66/8e8e81af-9eb2-41df-bfd5-4de96a4788f1)

**Comment by dckc** [comment]
Does transferring fees into the zoe fees purse address this?

See also https://github.com/Agoric/testnet-notes/issues/32 , https://github.com/Agoric/agoric-sdk/issues/3780

**Comment by samsiegart** [comment]
Fixed in https://github.com/Agoric/dapp-treasury/pull/51
