### ISSUE TITLE
Can't swap on https://treasury.agoric.app/swap

### ISSUE THREAD

**Issue by jjangg96** [Agoric/dapp-treasury#25]
I followed the documentation. 
https://github.com/Agoric/agoric-sdk/wiki/Setting-up-an-Agoric-Dapp-Client-with-docker-compose
Running ag-solo and connecting treasury looks fine.
<img width="713" alt="image" src="https://user-images.githubusercontent.com/927149/117344578-7c860f80-aee0-11eb-834c-dab7ecc3e2ba.png">

<img width="775" alt="image" src="https://user-images.githubusercontent.com/927149/117344478-61b39b00-aee0-11eb-9285-3db01a5a891f.png">

But when I tried to swap RUN to BLD, the Output input box didn't get filled.

<img width="794" alt="image" src="https://user-images.githubusercontent.com/927149/117343799-9f63f400-aedf-11eb-80e2-61e0c25896b0.png">

Also, I found a console.log message from the browser inspector.
```
ALL {purses: Array(5), inputPurse: {…}, outputPurse: {…}, inputAmount: {…}, outputAmount: null, …}
lockdown.umd.js:4508 RATES {brand: Alleged: RUN brand, ratio: {…}} {brand: Alleged: BLD brand, ratio: null}
lockdown.umd.js:4508 RATES {brand: Alleged: RUN brand, ratio: {…}} {brand: Alleged: BLD brand, ratio: null} null
lockdown.umd.js:4508 Amount display null {brand: Alleged: RUN brand, value: 1000000n} undefined Input
lockdown.umd.js:4508 Amount display {brand: Alleged: RUN brand, value: 1000000n} null undefined Output
lockdown.umd.js:4508 DISPLAY AMOUNTS {inputDisplay: 1000000n, outputDisplay: null, marketRate: null, connected: true, hasError: null, …}
lockdown.umd.js:4508 QUOTING true Alleged: BLD brand {} {brand: Alleged: RUN brand, value: 1000000n}
lockdown.umd.js:4508 send: CTP_CALL ["getPriceGivenAvailableInput",[{"brand":{"@qclass":"slot","iface":"Alleged: RUN brand","index":0},"value":{"@qclass":"bigint","digits":"1000000"}},{"@qclass":"slot","iface":"Alleged: BLD brand","index":1}]] {type: "CTP_CALL", epoch: 0, questionID: 130, target: "o-35", method: {…}}
```

@dckc

**Comment by katelynsills** [comment]
Thanks for this report @jjangg96! 

I was able to reproduce, but I think the issue might be temporary while a request is made to the chain. How long does the Output box remain empty for you, @jjangg96? For me, it was about 30 seconds or so.

While the price query is still outstanding:
<img width="835" alt="Screen Shot 2021-05-06 at 2 23 11 PM" src="https://user-images.githubusercontent.com/2441069/117367257-cdf9b480-ae76-11eb-999b-7e03f94cf509.png">

After the result is obtained:

<img width="860" alt="Screen Shot 2021-05-06 at 2 23 18 PM" src="https://user-images.githubusercontent.com/2441069/117367254-ccc88780-ae76-11eb-86b9-f37948ad8881.png">

**Comment by jjangg96** [comment]
> just in case, what browser, operating system, and that sort of thing were you using, @jjangg96 ?

Brave Browser, OSX(Big Sur), Docker-Composer to run.

**Comment by jjangg96** [comment]
Waiting more than a few minutes does not change anything.

**Comment by michaelfig** [comment]
> Waiting more than a few minutes does not change anything.
> That's why I checked the browser inspector log. Look like the null value is coming from API.

Can you please post a screenshot of the inspector?

**Comment by michaelfig** [comment]
> > just in case, what browser, operating system, and that sort of thing were you using, @jjangg96 ?
> 
> Brave Browser, OSX(Big Sur), Docker-Composer to run.

Sometimes we found that Brave needs to unblock "trackers and ads" to work.  We have plans to fix that, but that's the current state.

**Comment by dckc** [comment]
a screenshot is more useful than the text from the console in the issue comment? What are you looking for, @michaelfig ?

**Comment by michaelfig** [comment]
> a screenshot is more useful than the text from the console in the issue comment? What are you looking for, @michaelfig ?

Oh, I'm being silly.  But what I would like is the complete transcript from the console, not just the last few things.

**Comment by jjangg96** [comment]
```
lockdown.umd.js:4508 ALL {purses: Array(5), inputPurse: {…}, outputPurse: {…}, inputAmount: {…}, outputAmount: null, …}connected: trueinputAmount: {brand: Alleged: RUN brand, value: 5000000n}inputPurse: {brand: Alleged: RUN brand, brandBoardId: "1532665031", brandPetname: "RUN", currentAmount: {…}, currentAmountSlots: {…}, …}outputAmount: nulloutputPurse: {brand: Alleged: BLD brand, brandBoardId: "379944443", brandPetname: "BLD", currentAmount: {…}, currentAmountSlots: {…}, …}purses: (5) [{…}, {…}, {…}, {…}, {…}]constructor: (...)hasOwnProperty: (...)isPrototypeOf: (...)propertyIsEnumerable: (...)toLocaleString: (...)toString: (...)valueOf: (...)__defineGetter__: (...)__defineSetter__: (...)__lookupGetter__: (...)__lookupSetter__: (...)__proto__: Object
lockdown.umd.js:4508 RATES {brand: Alleged: RUN brand, ratio: {…}} {brand: Alleged: BLD brand, ratio: null}
lockdown.umd.js:4508 RATES {brand: Alleged: RUN brand, ratio: {…}} {brand: Alleged: BLD brand, ratio: null} null
lockdown.umd.js:4508 Amount display null {brand: Alleged: RUN brand, value: 5000000n} undefined Input
lockdown.umd.js:4508 Amount display {brand: Alleged: RUN brand, value: 5000000n} null undefined Output
lockdown.umd.js:4508 DISPLAY AMOUNTS {inputDisplay: 5000000n, outputDisplay: null, marketRate: null, connected: true, hasError: null, …}
lockdown.umd.js:4508 QUOTING true Alleged: BLD brand {} {brand: Alleged: RUN brand, value: 5000000n}
lockdown.umd.js:4508 send: CTP_CALL ["getPriceGivenAvailableInput",[{"brand":{"@qclass":"slot","iface":"Alleged: RUN brand","index":0},"value":{"@qclass":"bigint","digits":"5000000"}},{"@qclass":"slot","iface":"Alleged: BLD brand","index":1}]] {type: "CTP_CALL", epoch: 0, questionID: 138, target: "o-35", method: {…}}
```

<img width="1589" alt="image" src="https://user-images.githubusercontent.com/927149/117387614-26d35680-af24-11eb-99be-cbf162524d51.png">

**Comment by michaelfig** [comment]
Were there any messages before the "ALL" one?

**Comment by michaelfig** [comment]
> ouputAmount is null.

What I'm trying to understand is if your ag-solo is connected to the chain.  The last message being `CTP_CALL` without a `CTP_RETURN` means that the call to the chain is not coming back.

**Comment by jjangg96** [comment]
When I tried again. Output filled.
I attached the full log of docker-composer.
[ag-solo-log.txt](https://github.com/Agoric/dapp-treasury/files/6438599/ag-solo-log.txt)

**Comment by michaelfig** [comment]
> When I tried again. Output filled.
> I attached the full log of docker-composer.
> [ag-solo-log.txt](https://github.com/Agoric/dapp-treasury/files/6438599/ag-solo-log.txt)

We can continue on Discord, but I was curious, did you have to rerun `docker-compose up` in order to make it work?
