### ISSUE TITLE
AMM swaps are failing consistently

### ISSUE THREAD

**Issue by rowgraus** [Agoric/dapp-treasury#28]
Have made 5 consecutive attempts at swaps at lower and lower amounts (to try to control for slippage) and all have failed.  Failure is silent to the user unless he/she is watching the logs.  Seems like it's in the Zoe layer?  It's possible that price movements on the AMM are causing it but I can't verify that directly.

Here is the error I'm receiving in the logs:
2021-05-07T18:49:22.752Z chain-cosmos-sdk: gas estimate: 45693
ag-solo_1  | UnhandledPromiseRejectionWarning: (RemoteError(error:liveSlots:v11#70071)#57)
ag-solo_1  | RemoteError(error:liveSlots:v11#70071)#57: rights were not conserved for brand (an object)
ag-solo_1  | 
ag-solo_1  |   at fullRevive (packages/marshal/src/marshal.js:526:43)
ag-solo_1  |   at meteredConstructor.unserialize (packages/marshal/src/marshal.js:609:19)
ag-solo_1  |   at notifyOnePromise (packages/SwingSet/src/kernel/liveSlots.js:720:19)
ag-solo_1  |   at notify (packages/SwingSet/src/kernel/liveSlots.js:733:7)
ag-solo_1  |   at dispatchToUserspace (packages/SwingSet/src/kernel/liveSlots.js:843:11)
ag-solo_1  | 
ag-solo_1  | RemoteError(error:liveSlots:v11#70071)#57 ERROR_NOTE: Rejection from: (Error#58) : 14339 . 0
ag-solo_1  | Nested error under RemoteError(error:liveSlots:v11#70071)#57
ag-solo_1  |   Error#58: Event: 14337.2
ag-solo_1  |   
ag-solo_1  |     at Function.applyMethod (packages/tame-metering/src/tame.js:202:19)
ag-solo_1  |     at Proxy.eval (packages/eventual-send/src/E.js:37:126)
ag-solo_1  |     at meteredConstructor.acceptOffer (packages/dapp-svelte-wallet/api/src/lib-wallet.js:1029:51)

Might need to troubleshoot with someone live.  It's easy to reproduce.

**Comment by katelynsills** [comment]
What's the offer being made? Can you post a screenshot of your offer to be approved in the wallet?

**Comment by rowgraus** [comment]
Fresh run-through with screenshots of offer being made and entirety of ag-solo logs.  Apologies for length.

![image](https://user-images.githubusercontent.com/60824328/117497171-18963200-af46-11eb-8530-bf82efb98680.png)
![image](https://user-images.githubusercontent.com/60824328/117497258-42e7ef80-af46-11eb-931c-cdfe67bffbf8.png)
![image](https://user-images.githubusercontent.com/60824328/117497331-5f842780-af46-11eb-80d9-453bd86e51fc.png)
![image](https://user-images.githubusercontent.com/60824328/117497414-762a7e80-af46-11eb-8eba-50d6393ae5e5.png)
![image](https://user-images.githubusercontent.com/60824328/117497437-7dea2300-af46-11eb-9b03-59ad41ff1713.png)
![image](https://user-images.githubusercontent.com/60824328/117497470-8a6e7b80-af46-11eb-8f74-37e2bd97f227.png)
![image](https://user-images.githubusercontent.com/60824328/117497508-96f2d400-af46-11eb-85b2-e482c5f313ff.png)

**Comment by katelynsills** [comment]
Here's a scenario that we can use in unit tests:

Pool allocation:
```
{
  Central: {
    brand: Alleged: RUN brand <[Object: null prototype] [Alleged: RUN brand] {}> [Alleged: RUN brand] {},
    value: 50825056949339n
  },
  Liquidity: {
    brand: Alleged: BLDLiquidity brand <[Object: null prototype] [Alleged: BLDLiquidity brand] {}> [Alleged: BLDLiquidity brand] {},
    value: 0n
  },
  Secondary: {
    brand: Alleged: BLD brand <[Object: null prototype] [Alleged: BLD brand] {}> [Alleged: BLD brand] {},
    value: 2196247730468n
  }
}
```
Code:
```
  const priceQuote = await E(publicFacet).getPriceGivenAvailableInput(amountMath.make(runBrand, 73000000n), bldBrand);
  
  console.log('price quote', priceQuote);

  const proposal = harden({
    give: { In: priceQuote.amountIn },
    want: { Out: priceQuote.amountOut },
  });
  const payment = harden({ In: E(runPurse).withdraw(priceQuote.amountIn) });
  
  const seatP = E(zoe).offer(
    E(publicFacet).makeSwapInInvitation(),
    proposal,
    payment,
  );

  const offerResult = await E(seatP).getOfferResult();
  ```
  
  Quoted price:
  
```
{
  amountIn: {
    brand: Alleged: RUN brand <[Object: null prototype] [Alleged: RUN brand] {}> [Alleged: RUN brand] {},
    value: 72999951n
  },
  amountOut: {
    brand: Alleged: BLD brand <[Object: null prototype] [Alleged: BLD brand] {}> [Alleged: BLD brand] {},
    value: 3145005n
  }
}
```

Error:
```
CapTP bundle exception: (RemoteError(error:captp:http://127.0.0.1#20001)#1)
RemoteError(error:captp:http://127.0.0.1#20001)#1: The reallocation was not offer safe
```

**Comment by katelynsills** [comment]
This was fixed by @Chris-Hibbert in https://github.com/Agoric/agoric-sdk/pull/3060/
