### ISSUE TITLE
Error when creating vault with 150% collateralization

### ISSUE THREAD

**Issue by samsiegart** [Agoric/dapp-treasury#48]
Trying to create a vault with the default 150% collateralization fails with the following error:

```
Error#1: Requested {"brand":"[Alleged: RUN brand]","value":"[1000100n]"} exceeds max {"brand":"[Alleged: RUN brand]","value":"[999995n]"}
```
When creating with 151%, it succeeds, but displays 150% on the created vault. Perhaps some sort of rounding error.

**Comment by Chris-Hibbert** [comment]
A recent change to the vaults switched to being explicit with `floorMultiplyBy` and `ceilingMultiplyBy`, and also being more conservative about the ratios. I would guess that `VaultConfigure.jsx` should use `ceiling` operations in `computeToLock()` rather than `floor` operations.
