### ISSUE TITLE
Implement getRUN view

### ISSUE THREAD

**Issue by samsiegart** [Agoric/dapp-treasury#64]
## Description

The UI should have a separate view for `getRUN` that works end-to-end.

The UI should interface with the backend similar to https://github.com/Agoric/agoric-sdk/blob/dc-run-loc/packages/treasury/test/test-runLoC.js

A few key differences compared to the create/manage vault UI:
- Liquidation ratio is not applicable, though there should be some indication of the maximum amount of RUN that can be borrowed.
- No need to select collateral since it's always BLD from the virtual purse. It should start from the equivalent of the "manage vault" page regardless of if any RUN is borrowed.

This may require separate work on the wallet UI to let dapps propose offers with attestations. Likely the wallet will UI will need to get an attestation, of the amount specified by the dapp, from the wallet backend before making the offer to receive RUN. Ideally these would be done in what looks like one step in the wallet UI.

## Acceptance Criteria

The user can go to treasury.agoric.app and:

- Borrow some amount of RUN with the getRUN protocol
- Pay back some or all of the RUN
- Borrow more RUN up to the maximum based on their locked BLD
- Lock or unlock BLD up to the maximum based on the amount of RUN borrowed

**Comment by samsiegart** [comment]
cc @turadg

**Comment by Tartuffo** [comment]
@samsiegart to turn this into an epic, with estimates on the sub issues.

**Comment by dckc** [comment]
@samsiegart @turadg as an example of what we were discussing, these sync up the brand keywords via a `RunStakeTerms` type.

https://github.com/Agoric/dapp-treasury/tree/dc-runStake-integration e94a8a1
https://github.com/Agoric/agoric-sdk/tree/dc-runStake-ui-support [0d1ad2b](https://github.com/Agoric/agoric-sdk/commit/0d1ad2b2e50155039f14801889440c6eb25c4e65)
