### ISSUE TITLE
Typing in negative value breaks the UI in autoswap

### ISSUE THREAD

**Issue by arirubinstein** [Agoric/dapp-treasury#92]
Typing in a negative value (-1) in the autoswap ui yields an error and removes the component from the page.

on commit: e070dc2f858db387dedb252137ae190dd7f48235

Reproduction steps:
1. launch vaultfactory
2. click autoswap
3. type `-1` in the first input field
4. component is removed with stack

https://user-images.githubusercontent.com/22369/158084318-56d341b9-e5a4-4ffe-9dc5-372ecce0feee.mov

**Comment by arirubinstein** [comment]
This appears to affect all amount components as well:
<img width="531" alt="Screen Shot 2022-03-13 at 4 45 34 PM" src="https://user-images.githubusercontent.com/22369/158084562-cd5094da-dca1-4bfc-b5bc-42422e89388e.png">

**Comment by samsiegart** [comment]
fixed
